// lib/exportSummary.ts
//
// Client-side export for FR-04.3 (Summary Export). All three functions are
// pure browser operations — no backend endpoint required:
//   - downloadMarkdown        -> triggers a .md file download
//   - copySummaryToClipboard  -> writes a formatted plain-text version to the clipboard
//   - exportSummaryAsPdf      -> opens a print-styled window; user saves as PDF via the browser dialog
//
// All three take the same shape so they can be called interchangeably from
// the Summary panel with the real `DocumentSummary` result and document title.

export interface ExportableSummary {
  overview: string;
  key_points: string[];
  entities: string[];
}

function buildMarkdown(title: string, summary: ExportableSummary): string {
  const lines: string[] = [];
  lines.push(`# Summary — ${title}`);
  lines.push("");
  lines.push("## Overview");
  lines.push(summary.overview.trim());
  lines.push("");

  if (summary.key_points.length > 0) {
    lines.push("## Key Points");
    for (const point of summary.key_points) {
      lines.push(`- ${point}`);
    }
    lines.push("");
  }

  if (summary.entities.length > 0) {
    lines.push("## Entities");
    lines.push(summary.entities.join(", "));
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated by DocuSense AI on ${new Date().toLocaleString()}_`);

  return lines.join("\n");
}

function safeFileSlug(title: string): string {
  return (
    title
      .trim()
      .replace(/\.[a-zA-Z0-9]+$/, "") // drop file extension if title is a filename
      .replace(/[^a-zA-Z0-9-_]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "") || "document"
  );
}

/** Triggers a browser download of the summary as a .md file. No backend call. */
export function downloadMarkdown(title: string, summary: ExportableSummary): void {
  const markdown = buildMarkdown(title, summary);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `${safeFileSlug(title)}-summary.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  URL.revokeObjectURL(url);
}

/**
 * Copies a formatted plain-text version of the summary to the clipboard.
 * Returns true on success, false if the Clipboard API was unavailable or denied.
 */
export async function copySummaryToClipboard(
  title: string,
  summary: ExportableSummary
): Promise<boolean> {
  const lines: string[] = [];
  lines.push(`Summary — ${title}`);
  lines.push("");
  lines.push("Overview:");
  lines.push(summary.overview.trim());

  if (summary.key_points.length > 0) {
    lines.push("");
    lines.push("Key Points:");
    for (const point of summary.key_points) {
      lines.push(`• ${point}`);
    }
  }

  if (summary.entities.length > 0) {
    lines.push("");
    lines.push(`Entities: ${summary.entities.join(", ")}`);
  }

  const text = lines.join("\n");

  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    throw new Error("Clipboard API unavailable");
  } catch {
    // Fallback for non-secure contexts / older browsers.
    try {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.focus();
      textarea.select();
      const ok = document.execCommand("copy");
      document.body.removeChild(textarea);
      return ok;
    } catch {
      return false;
    }
  }
}

/**
 * Opens a clean, print-styled window containing the summary and triggers the
 * browser's print dialog. The user selects "Save as PDF" as the destination.
 * Avoids needing a server-side PDF generation library or endpoint.
 */
export function exportSummaryAsPdf(title: string, summary: ExportableSummary): void {
  const printWindow = window.open("", "_blank", "width=800,height=1000");
  if (!printWindow) {
    // Popup blocked — caller should surface a message to the user.
    throw new Error(
      "Couldn't open the print window. Please allow pop-ups for this site and try again."
    );
  }

  const escapeHtml = (s: string) =>
    s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

  const keyPointsHtml =
    summary.key_points.length > 0
      ? `<h2>Key Points</h2><ul>${summary.key_points
          .map((p) => `<li>${escapeHtml(p)}</li>`)
          .join("")}</ul>`
      : "";

  const entitiesHtml =
    summary.entities.length > 0
      ? `<h2>Entities</h2><p class="entities">${summary.entities
          .map((e) => escapeHtml(e))
          .join(", ")}</p>`
      : "";

  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Summary — ${escapeHtml(title)}</title>
<style>
  @page { margin: 2.5cm; }
  body {
    font-family: Georgia, 'Times New Roman', serif;
    color: #1a1a1a;
    line-height: 1.6;
    max-width: 700px;
    margin: 0 auto;
    padding: 2rem;
  }
  h1 {
    font-size: 1.5rem;
    border-bottom: 2px solid #1a1a1a;
    padding-bottom: 0.5rem;
    margin-bottom: 1.5rem;
  }
  h2 {
    font-size: 1.05rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #444;
    margin-top: 1.75rem;
    margin-bottom: 0.5rem;
  }
  p { margin: 0 0 1rem 0; }
  ul { margin: 0; padding-left: 1.25rem; }
  li { margin-bottom: 0.4rem; }
  .entities { font-family: monospace; font-size: 0.9rem; }
  .footer {
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid #ccc;
    font-size: 0.75rem;
    color: #888;
  }
</style>
</head>
<body>
  <h1>Summary — ${escapeHtml(title)}</h1>
  <h2>Overview</h2>
  <p>${escapeHtml(summary.overview.trim())}</p>
  ${keyPointsHtml}
  ${entitiesHtml}
  <div class="footer">Generated by DocuSense AI on ${new Date().toLocaleString()}</div>
</body>
</html>`.trim();

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();

  // Give the new document a beat to finish rendering before invoking print.
  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
  };
}